project:
  type: book

execute:
  freeze: auto

book:
  title: "Introdução à acessibilidade urbana"
  subtitle: "um guia prático em R"
  author: "Rafael H. M. Pereira, Daniel Herszenhut" 
  date: today
  lang: pt
  cover-image: images/cover.png
  site-url: https://ipeagit.github.io/aop_curso
  repo-url: https://github.com/ipeaGIT/aop_curso
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  twitter-card: true
  open-graph: true
  google-analytics:
    tracking-id: "G-YVERJQF9PJ"
    anonymize-ip: true

  chapters:
    - index.qmd
    - part: s1_intro.qmd
      chapters:
        - 1_conceito.qmd
        - 2_indicadores.qmd
    - part: s2_calculo.qmd
      chapters:
        - 3_calculando_acesso.qmd
    - part: s3_dados_tp.qmd
      chapters:
        - 4_dados_gtfs.qmd
        - 5_gtfstools.qmd
    - part: s4_avaliacao_impacto.qmd
      chapters:
        - 6_cenarios_transporte.qmd
    - part: s5_dados_aop.qmd
      chapters:
        - 7_aopdata_populacao.qmd
        - 8_aopdata_uso_solo.qmd
        - 9_aopdata_acessibilidade.qmd
    - references.qmd

  page-navigation: true
  page-footer: 
    border: false
    left: "Copyright 2022, Ipea (Institute for Applied Economic Research)" 
    right: 
      - icon: github
        href: https://github.com/ipeaGIT/aop_curso

bibliography: references.bib

format:
  html:
    theme: cosmo
    cover-image: images/cover.png
    code-link: true
  pdf:
    documentclass: scrreprt

editor_options:
  markdown:
    wrap: 80
    canonical: true

theme:
  light: flatly
  dark: darkly
  
