project:
  type: book
  output-dir: docs

book:
  title: "Acessibilidade urbana e avaliação de impacto"
  author: "Rafael Pererira, ..."
  date: "5/21/2022"
  lang: pt
  cover-image: /images/cover.png
  site-url: https://rstudio-education.github.io/hopr/
  repo-url: https://github.com/ipeaGIT/aop_curso/tree/main/aop_curso_pt/
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]

  chapters:
    - index.qmd
    - part: 1_intro.qmd
      chapters:
        - 1a_conceito.qmd
        - 1b_indicadores.qmd
    - part: 2_dados_aop.qmd
      chapters:
        - 2a_populacao.qmd
        - 2b_uso_solo.qmd
        - 2c_acessibilidade.qmd
    - part: "PARTE 3: Dados de transporte público GTFS"
      chapters:
        - 3_dados_gtfs.qmd
    - part: "PARTE 4: Calculando acessibilidade"
      chapters:
        - 4_calculando_acesso.qmd
    - part: "PARTE 5: Avaliação de impacto"
      chapters:
        - 5a_cenarios_transporte.qmd
        - 5b_cenarios_uso_solo.qmd
    - references.qmd
  appendices:
    - nocoes_r.qmd

  page-navigation: true
  page-footer: 
    border: false
    background: light
    left: "Copyright 2021, Norah Jones" 
    right: 
      - icon: github
        href: https://github.com/ipeaGIT/aop_curso/tree/main/aop_curso_pt
      - icon: twitter 
        href: https://twitter.com/ 

bibliography: references.bib

format:
  html:
    theme: cosmo
    cover-image: /images/cover.png
    code-link: true
  pdf:
    documentclass: scrreprt

editor: visual

