on:
  workflow_dispatch:
  push:
    branches: [main, action-test]

name: build_binder

jobs:
  build_binderdeploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libudunits2-dev libgdal-dev libgeos-dev libproj-dev

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Java setup
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk

      - name: Java reconf
        run: sudo R CMD javareconf

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2

      - name: Move dependencies to Docker context
        run: |
          mkdir -p renv/cache
          cp -r ${RENV_PATHS_ROOT}/cache renv/cache

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ipea/intro_access_book:latest
