on:
  workflow_dispatch:
  push:
    branches: [main, action-test]

name: build_binder

jobs:
  build_binder:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create dependencies dir
        run: |
          mkdir -p /tmp/renv/cache

      - name: Restore renv cache
        uses: actions/cache@v3
        with:
          path: /renv/cache
          key: renv-cache-${{ runner.os }}-${{ github.run_id }}
          restore-keys: renv-cache-${{ runner.os }}-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ipea/intro_access_book:latest
