on:
  workflow_dispatch:
  push:
    branches: [main, action-test]

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Install system dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libudunits2-dev libgdal-dev libgeos-dev libproj-dev

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Java setup
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk

      - name: Java reconf
        run: sudo R CMD javareconf

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
